version: "3.4"
services:
  webserver:
    build:
      context: ./flaskServer
    ports:
      - "80:5000"
    links:
      - mysqldb
    restart: 'always'
    volumes:
      - ./flaskServer/webserver:/flaskProject
  mysqldb:
    image: mysql:latest
    restart: 'always'
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourSAFEpassword
      MYSQL_DATABASE: student
      MYSQL_USER: me
      MYSQL_PASSWORD: yourSAFEpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'Phpmyadmin'
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - '800:80'
